In [1]:
!pip install pyomo
from pyomo.environ import *
!wget -N -q "https://matematica.unipv.it/gualandi/solvers/ipopt-linux64.zip"
!unzip -o -q ipopt-linux64
!apt-get install -y -qq glpk-utils

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 22.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 5.5 MB/s eta 0:00:00
Selecting previously unselected package libsuitesparseconfig5:amd64.
(Reading database ... 121654 files and directories currently installed.)
Preparing to unpack .../libsuitesparseconfig5_1%3a5.10.1+dfsg-4build1_amd64.deb ...
Unpacking libsuitesparseconfig5:amd64 (1:5.10.1+dfsg-4build1) ...
Selecting previously unselected package libamd2:amd64.
Preparing to unpack .../libamd2_1%3a5.10.1+dfsg-4build1_amd64.deb ...
Unpacking libamd2:amd64 (1:5.10.1+dfsg-4build1) ...
Selecting previously unselected package libcolamd2:amd64.
Preparing to unpack .../libcolamd2_1%3a5.10.1+dfsg-4build1_amd64.deb ...
Unpacking libcolamd2:amd64 (1:5.10.1+dfsg-4build1) ...
Selecting previously unselected package libglpk40:amd64.
Preparing to unpack .../libglpk40_5.0-1_amd64.deb ...
Unpacking libglpk40:amd64 (5.0-1) ...
Selecting previously unselected pac

In [3]:
from pyomo.environ import *

model = ConcreteModel()

# Define the index set
model.I = RangeSet(1, 10)

# Define the decision variables
model.x = Var(model.I, domain=NonNegativeReals)

# Define the objective function
model.obj = Objective(
    expr=sum([2.5 * model.x[1] + 2.5 * model.x[2] + 1.6 * model.x[3] +
              2 * model.x[4] + 1.4 * model.x[5] + 1 * model.x[6] +
              0.8 * model.x[7] + model.x[8] + 1.4 * model.x[9] +
              0.8 * model.x[10]]),
    sense=minimize)

# Define the constraints
model.con1 = Constraint(expr=model.x[1] == 125)
model.con2 = Constraint(expr=model.x[2] == 175)
model.con3 = Constraint(expr=model.x[3] + model.x[4] == 225)
model.con4 = Constraint(expr=model.x[5] + model.x[6] == 250)
model.con5 = Constraint(expr=model.x[7] + model.x[8] == 225)
model.con6 = Constraint(expr=model.x[9] + model.x[10] == 200)
model.con7 = Constraint(expr=sum([model.x[i] for i in [2, 3, 5, 7, 9]]) <= 550)
model.con8 = Constraint(expr=sum([model.x[i] for i in [1, 4, 6, 8, 10]]) <= 700)

# Solve the model
solver = SolverFactory('glpk')
result = solver.solve(model)

# Display the solution
model.display()

# Print the objective value
print("Objective value:", value(model.obj))

Model unknown

  Variables:
    x : Size=10, Index=I
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          1 :     0 : 125.0 :  None : False : False : NonNegativeReals
          2 :     0 : 175.0 :  None : False : False : NonNegativeReals
          3 :     0 : 225.0 :  None : False : False : NonNegativeReals
          4 :     0 :   0.0 :  None : False : False : NonNegativeReals
          5 :     0 :   0.0 :  None : False : False : NonNegativeReals
          6 :     0 : 250.0 :  None : False : False : NonNegativeReals
          7 :     0 : 150.0 :  None : False : False : NonNegativeReals
          8 :     0 :  75.0 :  None : False : False : NonNegativeReals
          9 :     0 :   0.0 :  None : False : False : NonNegativeReals
         10 :     0 : 200.0 :  None : False : False : NonNegativeReals

  Objectives:
    obj : Size=1, Index=None, Active=True
        Key  : Active : Value
        None :   True : 1715.0

  Constraints:
    con1 : Size=1
        Key  : Lower : B

In [4]:
from pyomo.environ import *

model = ConcreteModel()

# Define the index set
model.I = RangeSet(1, 10)

# Define the decision variables
model.x = Var(model.I, domain=NonNegativeReals)

# Define the objective function
model.obj = Objective(
    expr=sum([2.5 * model.x[1] + 2.5 * model.x[2] + 1.6 * model.x[3] +
              2 * model.x[4] + 1.4 * model.x[5] + 1 * model.x[6] +
              0.8 * model.x[7] + model.x[8] + 1.4 * model.x[9] +
              0.8 * model.x[10]]),
    sense=minimize)

# Define the constraints
model.con1 = Constraint(expr=model.x[1] == 125)
model.con2 = Constraint(expr=model.x[2] == 175)
model.con3 = Constraint(expr=model.x[3] + model.x[4] == 225)
model.con4 = Constraint(expr=model.x[5] + model.x[6] == 250)
model.con5 = Constraint(expr=model.x[7] + model.x[8] == 225)
model.con6 = Constraint(expr=model.x[9] + model.x[10] == 200)
model.con7 = Constraint(expr=sum([model.x[i] for i in [2, 3, 5, 7, 9]]) <= 600)
model.con8 = Constraint(expr=sum([model.x[i] for i in [1, 4, 6, 8, 10]]) <= 650)

# Solve the model
solver = SolverFactory('glpk')
result = solver.solve(model)

# Display the solution
model.display()

# Print the objective value
print("Objective value:", value(model.obj))

Model unknown

  Variables:
    x : Size=10, Index=I
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          1 :     0 : 125.0 :  None : False : False : NonNegativeReals
          2 :     0 : 175.0 :  None : False : False : NonNegativeReals
          3 :     0 : 225.0 :  None : False : False : NonNegativeReals
          4 :     0 :   0.0 :  None : False : False : NonNegativeReals
          5 :     0 :   0.0 :  None : False : False : NonNegativeReals
          6 :     0 : 250.0 :  None : False : False : NonNegativeReals
          7 :     0 : 200.0 :  None : False : False : NonNegativeReals
          8 :     0 :  25.0 :  None : False : False : NonNegativeReals
          9 :     0 :   0.0 :  None : False : False : NonNegativeReals
         10 :     0 : 200.0 :  None : False : False : NonNegativeReals

  Objectives:
    obj : Size=1, Index=None, Active=True
        Key  : Active : Value
        None :   True : 1705.0

  Constraints:
    con1 : Size=1
        Key  : Lower : B

In [6]:
import numpy as np

# Define the variables
Q = np.array([[48, 12], [8, 8]])  # Matrix Q
q = np.array([[13], [23]])  # Vector q
p = 4  # Constant p
x_0 = np.array([[23], [37]])  # Initial guess for x

x_old = x_0

iteration = 1

# Calculate the gradient at x_old
gradient = np.dot(Q, x_old) + q
# Calculate alpha using the provided formula
alpha = np.dot(gradient.T, gradient) / np.dot(np.dot(gradient.T, Q), gradient)

print("alpha is : ",alpha)

while True:
    # Calculate the gradient at x_old
    gradient = np.dot(Q, x_old) + q

    # Update x_new using the gradient descent formula
    x_new = x_old - alpha * gradient

    # Calculate the difference between x_new and x_old
    diff = np.linalg.norm(x_new - x_old)

    # Print the current iteration's x, difference, and iteration number
    print("Iteration:", iteration)
    print("x =\n", x_new)
    print("Difference:", diff)
    print("-------------------")

    # Check if the difference is below the threshold
    if diff < 1e-6:
        break

    # Update x_old and iteration for the next iteration
    x_old = x_new
    iteration += 1

# Print the final updated value of x
print("Final updated value of x:")
print(x_new)
# Calculate the value of the objective function at x_new
f_x = 0.5 * np.dot(np.dot(x_new.T, Q), x_new) + np.dot(q.T, x_new) + p

# Print the value of the objective function at x_new
print("f(x_final):", f_x)

alpha is :  [[0.01996973]]
Iteration: 1
x =
 [[-8.17275174]
 [26.95522478]]
Difference: 32.75115204152204
-------------------
Iteration: 2
x =
 [[-7.05785386]
 [23.49527331]]
Difference: 3.6351425620357065
-------------------
Iteration: 3
x =
 [[-6.1825065 ]
 [20.40996257]]
Difference: 3.2070820557921507
-------------------
Iteration: 4
x =
 [[-5.40686691]
 [17.67771085]]
Difference: 2.840214120879622
-------------------
Iteration: 5
x =
 [[-4.71996641]
 [15.25804329]]
Difference: 2.5152779979294015
-------------------
Iteration: 6
x =
 [[-4.11165106]
 [13.11519888]]
Difference: 2.227516493223572
-------------------
Iteration: 7
x =
 [[-3.57293031]
 [11.21750754]]
Difference: 1.9726764716723286
-------------------
Iteration: 8
x =
 [[-3.09584214]
 [ 9.53692243]]
Difference: 1.7469915368674602
-------------------
Iteration: 9
x =
 [[-2.67333546]
 [ 8.04860542]]
Difference: 1.547126188056175
-------------------
Iteration: 10
x =
 [[-2.29916584]
 [ 6.73055997]]
Difference: 1.3701265239448

In [7]:
import numpy as np

# Define the variables
Q = np.array([[48, 12], [8, 8]])  # Matrix Q
q = np.array([[13], [23]])  # Vector q
p = 4  # Constant p
x_0 = np.array([[23], [37]])  # Initial guess for x

x_old = x_0

iteration = 1

while True:
    # Calculate the gradient at x_old
    gradient = np.dot(Q, x_old) + q

    # Calculate alpha using the provided formula
    alpha = np.dot(gradient.T, gradient) / np.dot(np.dot(gradient.T, Q), gradient)

    # Update x_new using the gradient descent formula
    x_new = x_old - alpha * gradient

    # Calculate the difference between x_new and x_old
    diff = np.linalg.norm(x_new - x_old)

    # Print the current iteration's x, difference, and iteration number
    print("Iteration:", iteration)
    print("x =\n", x_new)
    print("Difference:", diff)
    print("-------------------")

    # Check if the difference is below the threshold
    if diff < 1e-6:
        break

    # Update x_old and iteration for the next iteration
    x_old = x_new
    iteration += 1

# Print the final updated value of x
print("Final updated value of x:")
print(x_new)
# Calculate the value of the objective function at x_new
f_x = 0.5 * np.dot(np.dot(x_new.T, Q), x_new) + np.dot(q.T, x_new) + p

# Print the value of the objective function at x_new
print("f(x_final):", f_x)

Iteration: 1
x =
 [[-8.17275174]
 [26.95522478]]
Difference: 32.75115204152204
-------------------
Iteration: 2
x =
 [[ 1.25117731]
 [-2.29080553]]
Difference: 30.726873046166432
-------------------
Iteration: 3
x =
 [[ 0.34121963]
 [-2.58402059]]
Difference: 0.9560324515439509
-------------------
Iteration: 4
x =
 [[ 0.6163117 ]
 [-3.43773572]]
Difference: 0.8969421206729796
-------------------
Iteration: 5
x =
 [[ 0.5897493]
 [-3.4462949]]
Difference: 0.02790735566328681
-------------------
Iteration: 6
x =
 [[ 0.59777946]
 [-3.47121553]]
Difference: 0.026182461411827562
-------------------
Iteration: 7
x =
 [[ 0.59700408]
 [-3.47146538]]
Difference: 0.0008146381421037939
-------------------
Iteration: 8
x =
 [[ 0.59723849]
 [-3.47219284]]
Difference: 0.0007642870925351485
-------------------
Iteration: 9
x =
 [[ 0.59721585]
 [-3.47220013]]
Difference: 2.3779942126128878e-05
-------------------
Iteration: 10
x =
 [[ 0.5972227 ]
 [-3.47222136]]
Difference: 2.231015451963877e-05
------

In [8]:
import numpy as np

# Define the variables
Q = np.array([[48, 12], [8, 8]])  # Matrix Q
q = np.array([[13], [23]])  # Vector q
p = 4  # Constant p
x_0 = np.array([[23], [37]])  # Initial guess for x

x_old = x_0

iteration = 1
# Calculate alpha using the provided formula
alpha = 0.001

while True:
    # Calculate the gradient at x_old
    gradient = np.dot(Q, x_old) + q

    # Update x_new using the gradient descent formula
    x_new = x_old - alpha * gradient

    # Calculate the difference between x_new and x_old
    diff = np.linalg.norm(x_new - x_old)

    # Print the current iteration's x, difference, and iteration number
    print("Iteration:", iteration)
    print("x =\n", x_new)
    print("Difference:", diff)
    print("-------------------")

    # Check if the difference is below the threshold
    if diff < 1e-6:
        break

    # Update x_old and iteration for the next iteration
    x_old = x_new
    iteration += 1

# Print the final updated value of x
print("Final updated value of x:")
print(x_new)
# Calculate the value of the objective function at x_new
f_x = 0.5 * np.dot(np.dot(x_new.T, Q), x_new) + np.dot(q.T, x_new) + p

# Print the value of the objective function at x_new
print("f(x_final):", f_x)

Streaming output truncated to the last 5000 lines.
 [[ 0.59158929]
 [-3.45237972]]
Difference: 0.00011884925823048761
-------------------
Iteration: 1299
x =
 [[ 0.59162156]
 [-3.45249339]]
Difference: 0.00011816837765810424
-------------------
Iteration: 1300
x =
 [[ 0.59165365]
 [-3.45260642]]
Difference: 0.00011749139781128721
-------------------
Iteration: 1301
x =
 [[ 0.59168555]
 [-3.4527188 ]]
Difference: 0.00011681829634316849
-------------------
Iteration: 1302
x =
 [[ 0.59171727]
 [-3.45283053]]
Difference: 0.00011614905103507332
-------------------
Iteration: 1303
x =
 [[ 0.5917488 ]
 [-3.45294162]]
Difference: 0.00011548363979453573
-------------------
Iteration: 1304
x =
 [[ 0.59178016]
 [-3.45305208]]
Difference: 0.00011482204065682547
-------------------
Iteration: 1305
x =
 [[ 0.59181134]
 [-3.45316191]]
Difference: 0.00011416423178241512
-------------------
Iteration: 1306
x =
 [[ 0.59184234]
 [-3.4532711 ]]
Difference: 0.00011351019145765252
-------------------
Iterat

In [9]:
import numpy as np

# Define the variables
Q = np.array([[48, 12], [8, 8]])  # Matrix Q
q = np.array([[13], [23]])  # Vector q
p = 4  # Constant p
x_0 = np.array([[23], [37]])  # Initial guess for x

x_old = x_0

iteration = 1

while True:
    # Calculate the gradient at x_old
    gradient = np.dot(Q, x_old) + q

    # Calculate alpha using the provided formula
    alpha = 0.011

    # Update x_new using the gradient descent formula
    x_new = x_old - alpha * gradient

    # Calculate the difference between x_new and x_old
    diff = np.linalg.norm(x_new - x_old)

    # Print the current iteration's x, difference, and iteration number
    print("Iteration:", iteration)
    print("x =\n", x_new)
    print("Difference:", diff)
    print("-------------------")

    # Check if the difference is below the threshold
    if diff < 1e-6:
        break

    # Update x_old and iteration for the next iteration
    x_old = x_new
    iteration += 1

# Print the final updated value of x
print("Final updated value of x:")
print(x_new)
# Calculate the value of the objective function at x_new
f_x = 0.5 * np.dot(np.dot(x_new.T, Q), x_new) + np.dot(q.T, x_new) + p

# Print the value of the objective function at x_new
print("f(x_final):", f_x)

Iteration: 1
x =
 [[ 5.829]
 [31.467]]
Difference: 18.040435970341736
-------------------
Iteration: 2
x =
 [[-1.545356]
 [27.931952]]
Difference: 8.177878134151912
-------------------
Iteration: 3
x =
 [[-4.5594257 ]
 [25.35693155]]
Difference: 3.9642586242529205
-------------------
Iteration: 4
x =
 [[-5.64216389]
 [23.27375104]]
Difference: 2.34775702820783
-------------------
Iteration: 5
x =
 [[-5.87823649]
 [21.46917137]]
Difference: 1.8199555086234664
-------------------
Iteration: 6
x =
 [[-5.75145825]
 [19.8441691 ]]
Difference: 1.629940213056122
-------------------
Iteration: 7
x =
 [[-5.47711861]
 [18.35101054]]
Difference: 1.518151739692909
-------------------
Iteration: 8
x =
 [[-5.15053338]
 [16.96510805]]
Difference: 1.4238622222340658
-------------------
Iteration: 9
x =
 [[-4.81344602]
 [15.67242548]]
Difference: 1.3359102212118732
-------------------
Iteration: 10
x =
 [[-4.48370668]
 [14.46383529]]
Difference: 1.2527642565498638
-------------------
Iteration: 11
x =


In [10]:
import numpy as np

# Define the variables
Q = np.array([[48, 12], [8, 8]])  # Matrix Q
q = np.array([[13], [23]])  # Vector q
p = 4  # Constant p
x_0 = np.array([[23], [37]])  # Initial guess for x

x_old = x_0

iteration = 1

while True:
    # Calculate the gradient at x_old
    gradient = np.dot(Q, x_old) + q

    # Calculate alpha using the provided formula
    alpha = 0.035

    # Update x_new using the gradient descent formula
    x_new = x_old - alpha * gradient

    # Calculate the difference between x_new and x_old
    diff = np.linalg.norm(x_new - x_old)

    # Print the current iteration's x, difference, and iteration number
    print("Iteration:", iteration)
    print("x =\n", x_new)
    print("Difference:", diff)
    print("-------------------")

    # Check if the difference is below the threshold
    if diff < 1e-6:
        break

    # Update x_old and iteration for the next iteration
    x_old = x_new
    iteration += 1

# Print the final updated value of x
print("Final updated value of x:")
print(x_new)
# Calculate the value of the objective function at x_new
f_x = 0.5 * np.dot(np.dot(x_new.T, Q), x_new) + np.dot(q.T, x_new) + p

# Print the value of the objective function at x_new
print("f(x_final):", f_x)

Iteration: 1
x =
 [[-31.635]
 [ 19.395]]
Difference: 57.401387178360075
-------------------
Iteration: 2
x =
 [[12.9109]
 [22.0172]]
Difference: 44.62301132431563
-------------------
Iteration: 3
x =
 [[-18.481636]
 [ 11.432332]]
Difference: 33.1290016011458
-------------------
Iteration: 4
x =
 [[ 7.31093304]
 [12.60113712]]
Difference: 25.819037997022775
-------------------
Iteration: 5
x =
 [[-10.71891206]
 [  6.22075748]]
Difference: 19.125494991116696
-------------------
Iteration: 6
x =
 [[4.22114206]
 [6.67524076]]
Difference: 14.946965313366427
-------------------
Iteration: 7
x =
 [[-6.12897772]
 [ 2.81925357]]
Difference: 11.045072051941847
-------------------
Iteration: 8
x =
 [[2.52861835]
 [2.94097633]]
Difference: 8.658451716182496
-------------------
Iteration: 9
x =
 [[-3.40967054]
 [ 0.60448982]]
Difference: 6.381413959122385
-------------------
Iteration: 10
x =
 [[1.60969024]
 [0.58494042]]
Difference: 5.019398847852601
-------------------
Iteration: 11
x =
 [[-1.795

In [11]:
import numpy as np

# Define the variables
Q = np.array([[48, 12], [8, 8]])  # Matrix Q
q = np.array([[13], [23]])  # Vector q
p = 4  # Constant p
x_0 = np.array([[23], [37]])  # Initial guess for x

x_old = x_0

iteration = 1

while True:
    # Calculate the gradient at x_old
    gradient = np.dot(Q, x_old) + q

    # Calculate alpha using the provided formula
    alpha = 0.039

    # Update x_new using the gradient descent formula
    x_new = x_old - alpha * gradient

    # Calculate the difference between x_new and x_old
    diff = np.linalg.norm(x_new - x_old)

    # Print the current iteration's x, difference, and iteration number
    print("Iteration:", iteration)
    print("x =\n", x_new)
    print("Difference:", diff)
    print("-------------------")

    # Check if the difference is below the threshold
    if diff < 1e-6:
        break

    # Update x_old and iteration for the next iteration
    x_old = x_new
    iteration += 1

# Print the final updated value of x
print("Final updated value of x:")
print(x_new)
# Calculate the value of the objective function at x_new
f_x = 0.5 * np.dot(np.dot(x_new.T, Q), x_new) + np.dot(q.T, x_new) + p

# Print the value of the objective function at x_new
print("f(x_final):", f_x)

Iteration: 1
x =
 [[-37.879]
 [ 17.383]]
Difference: 63.96154571302979
-------------------
Iteration: 2
x =
 [[24.388244]
 [22.880752]]
Difference: 62.509478900475884
-------------------
Iteration: 3
x =
 [[-32.4817407 ]
 [  7.23582525]]
Difference: 58.98269994929563
-------------------
Iteration: 4
x =
 [[24.43071168]
 [14.21555087]]
Difference: 57.33885075475078
-------------------
Iteration: 5
x =
 [[-28.46345839]
 [  1.26091696]]
Difference: 54.457467505133934
-------------------
Iteration: 6
x =
 [[23.72302658]
 [ 8.85110988]]
Difference: 52.73556904385108
-------------------
Iteration: 7
x =
 [[-25.3357986 ]
 [ -2.20902069]]
Difference: 50.29010655145913
-------------------
Iteration: 8
x =
 [[22.61963807]
 [ 5.48796293]]
Difference: 48.56920282685978
-------------------
Iteration: 9
x =
 [[-22.79969104]
 [ -4.17860858]]
Difference: 46.43660260808317
-------------------
Iteration: 10
x =
 [[21.32991941]
 [ 3.3416209 ]]
Difference: 44.76579464511058
-------------------
Iteration: 

In [12]:
import numpy as np

# Define the variables
Q = np.array([[48, 12], [8, 8]])  # Matrix Q
q = np.array([[13], [23]])  # Vector q
p = 4  # Constant p
x_0 = np.array([[23], [37]])  # Initial guess for x

x_old = x_0

iteration = 1

while True:
    # Calculate the gradient at x_old
    gradient = np.dot(Q, x_old) + q

    # Calculate alpha using the provided formula
    alpha = 0.022

    # Update x_new using the gradient descent formula
    x_new = x_old - alpha * gradient

    # Calculate the difference between x_new and x_old
    diff = np.linalg.norm(x_new - x_old)

    # Print the current iteration's x, difference, and iteration number
    print("Iteration:", iteration)
    print("x =\n", x_new)
    print("Difference:", diff)
    print("-------------------")

    # Check if the difference is below the threshold
    if diff < 1e-6:
        break

    # Update x_old and iteration for the next iteration
    x_old = x_new
    iteration += 1

# Print the final updated value of x
print("Final updated value of x:")
print(x_new)
# Calculate the value of the objective function at x_new
f_x = 0.5 * np.dot(np.dot(x_new.T, Q), x_new) + np.dot(q.T, x_new) + p

# Print the value of the objective function at x_new
print("f(x_final):", f_x)

Iteration: 1
x =
 [[-11.342]
 [ 25.934]]
Difference: 36.08087194068347
-------------------
Iteration: 2
x =
 [[-6.497424]
 [22.859808]]
Difference: 5.737645255036249
-------------------
Iteration: 3
x =
 [[-5.95713357]
 [19.47402842]]
Difference: 3.4286173805693085
-------------------
Iteration: 4
x =
 [[-5.09354402]
 [16.58905492]]
Difference: 3.0114546253723344
-------------------
Iteration: 5
x =
 [[-4.38027203]
 [14.059845  ]]
Difference: 2.627862199648884
-------------------
Iteration: 6
x =
 [[-3.75250385]
 [11.85024016]]
Difference: 2.2970516880762974
-------------------
Iteration: 7
x =
 [[-3.20432319]
 [ 9.91903857]]
Difference: 2.0074963567381494
-------------------
Iteration: 8
x =
 [[-2.72518408]
 [ 8.23124866]]
Difference: 1.754482559536669
-------------------
Iteration: 9
x =
 [[-2.30643934]
 [ 6.7561813 ]]
Difference: 1.5333528282625768
-------------------
Iteration: 10
x =
 [[-1.94047126]
 [ 5.46702671]]
Difference: 1.3400940929783773
-------------------
Iteration: 11
x